import 'package:flutter/material.dart';

const kMAinColor = Color(0xffffc12f);
const kSecondaryColor = Color(0xFFFFE6Ac);
const kUnActiveMode = Color(0xffc1bdb8) ;
const kCollectionName = "ProductCollection" ;
const kProductName ="productName" ;
const kProductPrice = "productPrice";
const kProductDescription = "productDescription";
const kProductCategory = "productCategory";
const kProductImageLocation  = "productImagelocation" ;
const kJackets = "jakets" ;
const kTrousers = "trousers" ;
const kT_Shirt = "shirt" ;
const kShose = "shose" ;
const kOrders = "orders" ;
const kOrderDetails = "orderDetails" ;
const kTotalPrice = "total price";
const kProductQuantity = "Quantity" ;
const kAddress = "address" ;
const kKeepMeLogin = "keepMeLogin" ;